### ISSUE TITLE
warn_level: :store need to rescue IDN::Idna::IdnaError

### ISSUE THREAD

**Issue by dentarg** [jaimeiniesta/metainspector#151]
This is when using native IDN support (see https://github.com/sporkmonger/addressable/blob/master/lib/addressable/idna.rb)

```ruby
[2] pry(main)> MetaInspector.new("http://blogs.channel4.com/factcheck/fact-check-43-eu-migrants-claim-benefits/21964", warn_level: :store).links.external
IDN::Idna::IdnaError: Output would be too large or too small (5)
from /Users/dentarg/.gem/ruby/2.2.3/gems/addressable-2.3.8/lib/addressable/idna/native.rb:38:in `toASCII'
```

Addressable is used at https://github.com/jaimeiniesta/metainspector/blob/fda1ba663fb5ac8f2abe7cd8d8526f38ca3d05b0/lib/meta_inspector/url.rb#L87

The problematic "URL" from that page

```ruby
[7] pry(main)> Addressable::URI.parse("http://at%205.05pm%20the%20department%20of%20work%20and%20pensions%20publis…t%20contain%20data%20tables%20or%20detailed%20figures%20to%20interrogate./").normalize.to_s

IDN::Idna::IdnaError: Output would be too large or too small (5)
from /Users/dentarg/.gem/ruby/2.2.3/gems/addressable-2.3.8/lib/addressable/idna/native.rb:38:in `toASCII'
```

```ruby
[2] pry(main)> Addressable::IDNA.to_ascii("http://at%205.05pm%20the%20department%20of%20work%20and%20pensions%20publis…t%20contain%20data%20tables%20or%20detailed%20figures%20to%20interrogate./").normalize.to_s

IDN::Idna::IdnaError: Output would be too large or too small (5)
from /Users/dentarg/.gem/ruby/2.2.3/gems/addressable-2.3.8/lib/addressable/idna/native.rb:38:in `toASCII'
```

The pure Ruby IDNA implementation doesn't have a problem here ([but it has other problems](https://github.com/sporkmonger/addressable/issues/215))

```ruby
[4] pry(main)> require "addressable/idna/pure"
=> true
[5] pry(main)> Addressable::IDNA.to_ascii("http://at%205.05pm%20the%20department%20of%20work%20and%20pensions%20publis…t%20contain%20data%20tables%20or%20detailed%20figures%20to%20interrogate./")
```

**Comment by jaimeiniesta** [comment]
Can you try this with 5.0.0 and see how it goes? It should raise a `MetaInspector::RequestError`.

**Comment by jaimeiniesta** [comment]
Tried this with MetaInspector 5.0.1, and it doesn't fail:

https://metainspectordemo.herokuapp.com/scrape?url=http%3A%2F%2Fblogs.channel4.com%2Ffactcheck%2Ffact-check-43-eu-migrants-claim-benefits%2F21964

Closing this, feel free to reopen if needed.

Thanks for the report!
