### ISSUE TITLE
Having trouble to create new instance of MetaInspector

### ISSUE THREAD

**Issue by yuvalIndie** [jaimeiniesta/metainspector#309]
Hey there , 
working with ruby 2.5 , rails 5.2
when try to do  page = MetaInspector.new('http://sitevalidator.com')
i get error of "ArgumentError (wrong number of arguments (given 1, expected 0))" 

thanks

**Comment by jaimeiniesta** [comment]
Hello!

What version of MetaInspector are you using?

**Comment by yuvalIndie** [comment]
Hey ! 
i tried using latest version 
also tried to install versions 5.11 , 5.5 and 3

**Comment by jaimeiniesta** [comment]
That's weird, can you try this outside the Rails environment? I mean, inside `irb`:

```
irb
require 'metainspector'
MetaInspector.new('http://sitevalidator.com/')
```

**Comment by yuvalIndie** [comment]
checked it  outside of Rails env and it works . 
any way to run it on rails ?

**Comment by jaimeiniesta** [comment]
Sure, it should work, many rails projects use metainspector.

Do you have a longer stack trace with the error? I don't see why this might fail.

Maybe you can reproduce that in a sample repo with your ruby and rails version so we can investigate more?

**Comment by yuvalIndie** [comment]
here is the stack trace ,
```
"/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/actionpack-5.2.2/lib/action_controller/metal/basic_implicit_render.rb:6:in`send_action'",
"/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/actionpack-5.2.2/lib/abstract_controller/base.rb:194:in`process_action'",
"/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/actionpack-5.2.2/lib/action_controller/metal/rendering.rb:30:in`process_action'",
"/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/actionpack-5.2.2/lib/abstract_controller/callbacks.rb:42:in`blockinprocess_action'",
"/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activesupport-5.2.2/lib/active_support/callbacks.rb:132:in`run_callbacks'",
"/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/actionpack-5.2.2/lib/abstract_controller/callbacks.rb:41:in`process_action'",
"/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/actionpack-5.2.2/lib/action_controller/metal/rescue.rb:22:in`process_action'",
"/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/actionpack-5.2.2/lib/action_controller/metal/instrumentation.rb:34:in`blockinprocess_action'",
"/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activesupport-5.2.2/lib/active_support/notifications.rb:168:in`blockininstrument'",
"/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activesupport-5.2.2/lib/active_support/notifications/instrumenter.rb:23:in`instrument'",
"/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activesupport-5.2.2/lib/active_support/notifications.rb:168:in`instrument'",
"/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/actionpack-5.2.2/lib/action_controller/metal/instrumentation.rb:32:in`process_action'",
"/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/actionpack-5.2.2/lib/action_controller/metal/params_wrapper.rb:256:in`process_action'",
"/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activerecord-5.2.2/lib/active_record/railties/controller_runtime.rb:24:in`process_action'",
"/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/actionpack-5.2.2/lib/abstract_controller/base.rb:134:in`process'",
"/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/actionpack-5.2.2/lib/action_controller/metal.rb:191:in`dispatch'",
"/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/actionpack-5.2.2/lib/action_controller/metal.rb:252:in`dispatch'",
"/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/actionpack-5.2.2/lib/action_dispatch/routing/route_set.rb:52:in`dispatch'",
"/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/actionpack-5.2.2/lib/action_dispatch/routing/route_set.rb:34:in`serve'",
"/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/actionpack-5.2.2/lib/action_dispatch/journey/router.rb:52:in`blockinserve'",
"/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/actionpack-5.2.2/lib/action_dispatch/journey/router.rb:35:in`each'",
"/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/actionpack-5.2.2/lib/action_dispatch/journey/router.rb:35:in`serve'",
"/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/actionpack-5.2.2/lib/action_dispatch/routing/route_set.rb:840:in`call'"
```

thanks again

**Comment by jaimeiniesta** [comment]
Thanks, but I don't see any trace of metainspector in that trace...

If you can share a rails app that reproduces the error, I can take another look.

**Comment by smlparry** [comment]
Am also seeing this issue in a rails console

Here is the trace:

```
wrong number of arguments (given 1, expected 0)
(pry):8:in `initialize'
(pry):8:in `new'
(pry):8:in `__pry__'
/bundle/vendor/ruby/2.7.0/gems/pry-0.14.0/lib/pry/pry_instance.rb:290:in `eval'
/bundle/vendor/ruby/2.7.0/gems/pry-0.14.0/lib/pry/pry_instance.rb:290:in `evaluate_ruby'
/bundle/vendor/ruby/2.7.0/gems/pry-0.14.0/lib/pry/pry_instance.rb:659:in `handle_line'
/bundle/vendor/ruby/2.7.0/gems/pry-0.14.0/lib/pry/pry_instance.rb:261:in `block (2 levels) in eval'
/bundle/vendor/ruby/2.7.0/gems/pry-0.14.0/lib/pry/pry_instance.rb:260:in `catch'
/bundle/vendor/ruby/2.7.0/gems/pry-0.14.0/lib/pry/pry_instance.rb:260:in `block in eval'
/bundle/vendor/ruby/2.7.0/gems/pry-0.14.0/lib/pry/pry_instance.rb:259:in `catch'
/bundle/vendor/ruby/2.7.0/gems/pry-0.14.0/lib/pry/pry_instance.rb:259:in `eval'
/bundle/vendor/ruby/2.7.0/gems/pry-0.14.0/lib/pry/repl.rb:77:in `block in repl'
/bundle/vendor/ruby/2.7.0/gems/pry-0.14.0/lib/pry/repl.rb:67:in `loop'
/bundle/vendor/ruby/2.7.0/gems/pry-0.14.0/lib/pry/repl.rb:67:in `repl'
/bundle/vendor/ruby/2.7.0/gems/pry-0.14.0/lib/pry/repl.rb:38:in `block in start'
/bundle/vendor/ruby/2.7.0/gems/pry-0.14.0/lib/pry/input_lock.rb:61:in `__with_ownership'
/bundle/vendor/ruby/2.7.0/gems/pry-0.14.0/lib/pry/input_lock.rb:78:in `with_ownership'
/bundle/vendor/ruby/2.7.0/gems/pry-0.14.0/lib/pry/repl.rb:38:in `start'
/bundle/vendor/ruby/2.7.0/gems/pry-0.14.0/lib/pry/repl.rb:15:in `start'
/bundle/vendor/ruby/2.7.0/gems/pry-0.14.0/lib/pry/pry_class.rb:188:in `start'
/bundle/vendor/ruby/2.7.0/gems/railties-6.1.3/lib/rails/commands/console/console_command.rb:70:in `start'
/bundle/vendor/ruby/2.7.0/gems/railties-6.1.3/lib/rails/commands/console/console_command.rb:19:in `start'
/bundle/vendor/ruby/2.7.0/gems/railties-6.1.3/lib/rails/commands/console/console_command.rb:102:in `perform'
/bundle/vendor/ruby/2.7.0/gems/thor-1.1.0/lib/thor/command.rb:27:in `run'
/bundle/vendor/ruby/2.7.0/gems/thor-1.1.0/lib/thor/invocation.rb:127:in `invoke_command'
/bundle/vendor/ruby/2.7.0/gems/thor-1.1.0/lib/thor.rb:392:in `dispatch'
/bundle/vendor/ruby/2.7.0/gems/railties-6.1.3/lib/rails/command/base.rb:69:in `perform'
/bundle/vendor/ruby/2.7.0/gems/railties-6.1.3/lib/rails/command.rb:50:in `invoke'
/bundle/vendor/ruby/2.7.0/gems/railties-6.1.3/lib/rails/commands.rb:18:in `<main>'
/bundle/vendor/ruby/2.7.0/gems/bootsnap-1.7.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
/bundle/vendor/ruby/2.7.0/gems/bootsnap-1.7.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
/bundle/vendor/ruby/2.7.0/gems/bootsnap-1.7.2/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/bundle/vendor/ruby/2.7.0/gems/bootsnap-1.7.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
/bundle/vendor/ruby/2.7.0/gems/bootsnap-1.7.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
/bundle/vendor/ruby/2.7.0/gems/activesupport-6.1.3/lib/active_support/dependencies.rb:332:in `block in require'
/bundle/vendor/ruby/2.7.0/gems/activesupport-6.1.3/lib/active_support/dependencies.rb:299:in `load_dependency'
/bundle/vendor/ruby/2.7.0/gems/activesupport-6.1.3/lib/active_support/dependencies.rb:332:in `require'
/app/bin/rails:9:in `<main>'
/bundle/vendor/ruby/2.7.0/gems/bootsnap-1.7.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:59:in `load'
/bundle/vendor/ruby/2.7.0/gems/bootsnap-1.7.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:59:in `load'
/bundle/vendor/ruby/2.7.0/gems/activesupport-6.1.3/lib/active_support/dependencies.rb:326:in `block in load'
/bundle/vendor/ruby/2.7.0/gems/activesupport-6.1.3/lib/active_support/dependencies.rb:299:in `load_dependency'
/bundle/vendor/ruby/2.7.0/gems/activesupport-6.1.3/lib/active_support/dependencies.rb:326:in `load'
/bundle/vendor/ruby/2.7.0/gems/spring-2.1.1/lib/spring/commands/rails.rb:6:in `call'
/bundle/vendor/ruby/2.7.0/gems/spring-2.1.1/lib/spring/command_wrapper.rb:38:in `call'
/bundle/vendor/ruby/2.7.0/gems/spring-2.1.1/lib/spring/application.rb:220:in `block in serve'
/bundle/vendor/ruby/2.7.0/gems/activesupport-6.1.3/lib/active_support/fork_tracker.rb:10:in `block in fork'
/bundle/vendor/ruby/2.7.0/gems/activesupport-6.1.3/lib/active_support/fork_tracker.rb:8:in `fork'
/bundle/vendor/ruby/2.7.0/gems/activesupport-6.1.3/lib/active_support/fork_tracker.rb:8:in `fork'
/bundle/vendor/ruby/2.7.0/gems/activesupport-6.1.3/lib/active_support/fork_tracker.rb:26:in `fork'
/bundle/vendor/ruby/2.7.0/gems/spring-2.1.1/lib/spring/application.rb:180:in `serve'
/bundle/vendor/ruby/2.7.0/gems/spring-2.1.1/lib/spring/application.rb:145:in `block in run'
/bundle/vendor/ruby/2.7.0/gems/spring-2.1.1/lib/spring/application.rb:139:in `loop'
/bundle/vendor/ruby/2.7.0/gems/spring-2.1.1/lib/spring/application.rb:139:in `run'
/bundle/vendor/ruby/2.7.0/gems/spring-2.1.1/lib/spring/application/boot.rb:19:in `<top (required)>'
/usr/local/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
/usr/local/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
-e:1:in `<main>'
```

I also don't see any mention of `MetaInspector` but perhaps its conflicting with another gem?

**Comment by jaimeiniesta** [comment]
Thanks for the report!

I can't reproduce that, it would help if you could try again with the latest version of MetaInspector, I just released 5.14.0

If if keeps failing, please provide a sample rails application where I can reproduce the error, and I'll investigate from there.

**Comment by jaimeiniesta** [comment]
@jeet-codecimal can you share what ruby and metainspector versions are you using?
